import { mkdir, writeFile, access } from 'node:fs/promises';
import { join } from 'node:path';

import * as p from '@clack/prompts';

import cliPackage from '../../package.json' with { type: 'json' };

export interface NewOptions {
  readonly projectDir: string;
  readonly defaults: boolean;
  readonly name?: string;
  readonly locale?: string;
  readonly theme?: string;
}

export interface ProjectParams {
  readonly name: string;
  readonly bio: string;
  readonly locale: string;
  readonly theme: string;
}

export function buildConfigYaml(params: ProjectParams): string {
  return `# EDIT THIS FILE
# This is the main input for your self-hosted perch profile.
# Most users only need to update this file and replace files in ./public/.

profile:
  # Required: the name shown at the top of the page.
  name: "${params.name}"

  # Short profile text. Keep it concise; the Editorial theme treats this as
  # a fallback when profile.md is not present.
  bio: "${params.bio}"

  # Long profile body. Markdown formatting is rendered by supported themes.
  markdown: "./profile.md"

  # Optional avatar. Put your image at public/avatar.png and uncomment this.
  # avatarUrl: "./public/avatar.png"

  # Primary links shown near your profile.
  links: []
  # - label: "GitHub"
  #   href: "https://github.com/yourname"
  #   description: "Code, OSS projects, and experiments."
  # - label: "Newsletter"
  #   href: "https://example.com/newsletter"
  #   description: "Monthly notes and essays."

site:
  # Social preview metadata. Replace these before publishing.
  title: "${params.name}"
  description: "Profile of ${params.name}."
  # url: "https://example.com" # canonical URL of this page
  ogImage: "./public/og.svg"
  favicon: "./public/favicon.svg"
  # twitterHandle: "@yourhandle"

# ja or en.
locale: ${params.locale}

# editorial is the recommended default. Other bundled themes:
# minimal, grid, card, timeline.
theme: ${params.theme}

# Replace this with your RSS / Atom / JSON Feed URLs.
feeds: []
  # - url: "https://your-blog.example/feed.xml"
  #   name: "My Blog"
  # - url: "https://zenn.dev/yourname/feed"
  #   name: "Zenn"
  # - url: "https://www.youtube.com/@yourchannel"
  #   name: "YouTube"

# Posts: markdown files in ./posts with frontmatter will be published as HTML.
posts:
  enabled: true
  dir: ./posts
  assetsDir: ./assets
  perPage: 10
  showInTimeline: true
`;
}

export function buildProfileMd(params: ProjectParams): string {
  return `# ${params.name}

${params.bio}

Add a longer introduction here. Markdown is supported, so you can use **emphasis**,
links, and lists.

- What you write about
- Where people can follow your work
- What kind of opportunities you want to hear about
`;
}

export function buildPostsHelloMd(): string {
  return `---
title: perch へようこそ
publishedAt: 2026-05-12
description: 最初の記事。Markdown で自由に書いてください。
tags: [welcome]
---

# はじめての記事

この記事は \`posts/\` ディレクトリの markdown ファイルから生成されます。
ファイルを編集して \`perch build\` を実行すると \`dist/posts/hello/index.html\` に出力されます。

好きなだけ Markdown を使って書いてください。記事を削除するときは \`posts/\` ディレクトリから削除するだけで大丈夫です。
`;
}

export function buildPackageJson(): string {
  return `${JSON.stringify(
    {
      name: 'perch-profile',
      private: true,
      version: '0.0.0',
      type: 'module',
      scripts: {
        build: 'perch build',
        dev: 'perch dev',
      },
      devDependencies: {
        '@perch-app/cli': cliPackage.version,
      },
      packageManager: 'pnpm@9.15.4',
      engines: {
        node: '>=22.0.0',
        pnpm: '>=9.0.0',
      },
    },
    null,
    2,
  )}\n`;
}

export function buildAgentsMd(): string {
  return `# perch profile project

This project is a self-hosted perch profile page. It is meant to be edited by a human or an AI agent by changing configuration and assets, not by editing generated output.

## Start Here

Start with \`perch.config.yaml\`. It is the source of truth for:

- profile name, bio fallback, avatar, links, and the path to \`profile.md\`
- site title, description, OGP image, favicon, and canonical URL
- locale and theme
- RSS / Atom / JSON Feed sources

Use \`profile.md\` for the longer profile body. Markdown formatting is rendered
by supported themes.

Use \`public/\` for user-owned assets:

- \`public/avatar.png\` for the profile image
- \`public/og.png\` or \`public/og.svg\` for social sharing
- \`public/favicon.svg\` for the browser icon

## Do Not Edit

Do not edit \`dist/\`. It is generated by the build command and can be deleted or recreated at any time.

Do not edit \`.perch/\`. It is local cache data.

## Build And Check

Run \`pnpm build\` after changing \`perch.config.yaml\` or files in \`public/\`:

\`\`\`bash
pnpm build
\`\`\`

For local preview, run:

\`\`\`bash
pnpm dev
\`\`\`

## Editing Rules For AI Agents

- Keep short structured settings in \`perch.config.yaml\`.
- Put the long profile body in \`profile.md\`.
- Prefer replacing assets in \`public/\` over hardcoding remote image URLs.
- Keep feed URLs as normal public RSS / Atom / JSON Feed URLs.
- Preserve YAML comments that explain how the user can customize the page.
- If adding a new theme, update \`theme:\` and explain the choice in the final response.
`;
}

export function buildReadmeMd(params: ProjectParams): string {
  return `# ${params.name}

This is a self-hosted perch profile page.

## Quick Start

1. Run \`pnpm install\`.
2. Edit \`perch.config.yaml\`.
3. Replace assets in \`public/\`.
4. Run \`pnpm build\`.
5. Publish the generated \`dist/\` directory.

## What To Edit

- \`perch.config.yaml\`: profile settings, links, site metadata, locale, theme, and feed URLs.
- \`profile.md\`: long profile body with Markdown formatting.
- \`public/avatar.png\`: optional profile image.
- \`public/og.png\` or \`public/og.svg\`: social preview image.
- \`public/favicon.svg\`: browser icon.

Do not edit \`dist/\`; it is generated output.

## Local Preview

\`\`\`bash
pnpm build
pnpm dev
\`\`\`

## Keeping RSS Fresh

perch generates static HTML. RSS updates are not reflected until a new build runs.

For an always-fresh profile, configure a scheduled build. See \`docs/deployment.md\`.

## AI Agents

If an AI agent is editing this profile, it should read \`AGENTS.md\` first.
`;
}

export function buildDeploymentMd(): string {
  return `# Deployment and Scheduled Rebuilds

perch is a static profile generator. It fetches RSS / Atom / JSON Feed sources during \`perch build\` and writes the result to \`dist/\`.

RSS updates are not reflected until a new build runs.

## Recommended Model

Use a scheduled job to rebuild and redeploy the site.

Typical flow:

\`\`\`text
schedule or manual trigger
  -> perch build
  -> publish dist/
\`\`\`

## GitHub Actions

This project includes \`.github/workflows/perch-build.yml\` as a starting point.

The workflow:

- runs on push
- runs on a schedule
- runs manually via workflow dispatch
- executes \`pnpm build\`
- uploads \`dist/\` as a deployable artifact

If you publish to GitHub Pages, add the official Pages deploy step after the artifact upload.

If you publish to Cloudflare Pages, replace the artifact upload step with:

\`\`\`bash
npx wrangler pages deploy dist --project-name <your-cloudflare-pages-project>
\`\`\`

Set \`CLOUDFLARE_API_TOKEN\` and \`CLOUDFLARE_ACCOUNT_ID\` as repository secrets before enabling Cloudflare deploys.

## Server Cron

On a VPS or another always-on machine, run:

\`\`\`cron
0 * * * * cd /path/to/profile && pnpm build && rsync -a dist/ /var/www/profile/
\`\`\`

Hourly is a good default. Daily is enough if your feeds update rarely.

## Manual Publish

For occasional updates:

\`\`\`bash
pnpm build
# then upload dist/ to your host
\`\`\`

## Files

- Edit \`perch.config.yaml\` and \`public/\`.
- Publish \`dist/\`.
- Do not edit \`dist/\` directly.
- Do not commit \`.perch/\`; it is local cache data.
`;
}

export function buildGithubWorkflowYaml(): string {
  return `name: Build perch profile

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    # Rebuild hourly so RSS updates are reflected in the published page.
    - cron: '0 * * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9.15.4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run perch build
        run: pnpm build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: perch-dist
          path: dist/
`;
}

export function buildOgSvg(name: string): string {
  // 1200x630 OG-spec placeholder. Replace with a real PNG for production:
  // X (Twitter) does not always render SVG OGP — ship a PNG variant before launch.
  const safe = name.replace(/[<>&"']/g, '');
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0f172a"/>
      <stop offset="100%" stop-color="#1e293b"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="630" fill="url(#bg)"/>
  <text x="600" y="300" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" font-size="96" font-weight="800" fill="#f8fafc" text-anchor="middle" dominant-baseline="central">${safe}</text>
  <text x="600" y="400" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" font-size="32" font-weight="400" fill="#94a3b8" text-anchor="middle" dominant-baseline="central">— powered by perch</text>
</svg>
`;
}

export function buildFaviconSvg(name: string): string {
  const initial = (name.trim().charAt(0) || '?').toUpperCase().replace(/[<>&"']/g, '');
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <rect width="64" height="64" rx="12" fill="#0f172a"/>
  <text x="32" y="32" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" font-size="36" font-weight="700" fill="#f8fafc" text-anchor="middle" dominant-baseline="central">${initial}</text>
</svg>
`;
}

async function directoryExists(dir: string): Promise<boolean> {
  try {
    await access(dir);
    return true;
  } catch {
    return false;
  }
}

export async function promptProjectParams(defaults: ProjectParams): Promise<ProjectParams> {
  p.intro('Create a new perch profile page');

  const responses = await p.group(
    {
      name: () =>
        p.text({ message: 'Display name', placeholder: 'My Name', defaultValue: defaults.name }),
      bio: () =>
        p.text({
          message: 'Short bio',
          placeholder: 'Welcome to my profile page.',
          defaultValue: defaults.bio,
        }),
      locale: () =>
        p.select({
          message: 'Default locale',
          options: [
            { value: 'ja', label: 'Japanese (ja)' },
            { value: 'en', label: 'English (en)' },
          ],
          initialValue: 'ja',
        }),
      theme: () =>
        p.select({
          message: 'Theme',
          options: [
            { value: 'editorial', label: 'Editorial — writing, expertise, and trust' },
            { value: 'minimal', label: 'Minimal — lightweight reading-first page' },
            { value: 'grid', label: 'Grid — media-rich post gallery' },
            { value: 'card', label: 'Card — social bio links and latest posts' },
            { value: 'timeline', label: 'Timeline — public activity log' },
          ],
          initialValue: 'editorial',
        }),
    },
    {
      onCancel: () => {
        p.cancel('Setup cancelled.');
        process.exit(0);
      },
    },
  );

  p.outro('Creating project...');

  return {
    name: responses.name,
    bio: responses.bio,
    locale: responses.locale,
    theme: responses.theme,
  };
}

export async function runNew(opts: NewOptions): Promise<void> {
  const exists = await directoryExists(opts.projectDir);
  if (exists) {
    throw new Error(`Directory already exists: ${opts.projectDir}`);
  }

  const defaultParams: ProjectParams = {
    name: opts.name ?? 'My Name',
    bio: 'Welcome to my profile page.',
    locale: opts.locale ?? 'ja',
    theme: opts.theme ?? 'editorial',
  };

  const params = opts.defaults ? defaultParams : await promptProjectParams(defaultParams);

  await mkdir(opts.projectDir, { recursive: true });
  await mkdir(join(opts.projectDir, 'public'), { recursive: true });
  await mkdir(join(opts.projectDir, 'docs'), { recursive: true });
  await mkdir(join(opts.projectDir, 'posts'), { recursive: true });
  await mkdir(join(opts.projectDir, 'assets'), { recursive: true });
  await mkdir(join(opts.projectDir, '.github', 'workflows'), { recursive: true });

  const configYaml = buildConfigYaml(params);
  await writeFile(join(opts.projectDir, 'package.json'), buildPackageJson(), 'utf8');
  await writeFile(join(opts.projectDir, 'perch.config.yaml'), configYaml, 'utf8');
  await writeFile(join(opts.projectDir, 'profile.md'), buildProfileMd(params), 'utf8');
  await writeFile(join(opts.projectDir, 'AGENTS.md'), buildAgentsMd(), 'utf8');
  await writeFile(join(opts.projectDir, 'README.md'), buildReadmeMd(params), 'utf8');
  await writeFile(join(opts.projectDir, 'docs', 'deployment.md'), buildDeploymentMd(), 'utf8');
  await writeFile(
    join(opts.projectDir, '.github', 'workflows', 'perch-build.yml'),
    buildGithubWorkflowYaml(),
    'utf8',
  );

  await writeFile(join(opts.projectDir, 'public', 'og.svg'), buildOgSvg(params.name), 'utf8');
  await writeFile(
    join(opts.projectDir, 'public', 'favicon.svg'),
    buildFaviconSvg(params.name),
    'utf8',
  );

  await writeFile(
    join(opts.projectDir, 'posts', '2026-05-12-hello.md'),
    buildPostsHelloMd(),
    'utf8',
  );

  const gitignore = `dist/\n.perch/\nnode_modules/\n`;
  await writeFile(join(opts.projectDir, '.gitignore'), gitignore, 'utf8');
}
