// @ts-check
import js from '@eslint/js';
import prettierConfig from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import unusedImports from 'eslint-plugin-unused-imports';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.astro/**',
      '**/.wrangler/**',
      '**/coverage/**',
      'pnpm-lock.yaml',
      '**/drizzle/migrations/**',
      // tsd runner reads these; tsc / ts-eslint should not.
      '**/tests/**/*.test-d.ts',
      // Generated by `paraglide-js compile` — checked in but not author code.
      'packages/i18n/src/paraglide/**',
      // Astro single-file components — typechecked separately by `astro check`.
      // typescript-eslint cannot parse `.astro` and `eslint-plugin-import`
      // crashes on the embedded frontmatter (TASK-0020).
      '**/*.astro',
      // Astro config — `eslint-plugin-import@2.32.0` is incompatible with
      // ESLint 10 and crashes on import/order for this file. Astro itself
      // typechecks the config via `astro check`. Re-evaluate when
      // `eslint-plugin-import` ships an ESLint 10 compatible release.
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            'eslint.config.js',
            'vitest.workspace.ts',
            'packages/cli/bin/*.mjs',
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      import: importPlugin,
      'unused-imports': unusedImports,
    },
    rules: {
      'import/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'type'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'unused-imports/no-unused-imports': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  // Keep @perch/core framework-agnostic.
  {
    files: ['packages/core/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['cloudflare:*'],
              message:
                '@perch/core must not depend on Cloudflare runtime bindings. Use the injected Storage/OgStore interface instead.',
            },
          ],
        },
      ],
    },
  },
  // Tooling JS / MJS files — disable type-checked rules and add Node globals.
  {
    files: ['eslint.config.js', '**/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
    },
  },
  prettierConfig,
);
